dist: trusty
compiler: gcc

services:
  - docker

notifications:
  email: false

addons:
  apt:
    packages:
      - wget

script:
  - docker run -v $PWD:/sources -w /sources conanio/gcc48 ci/docker_build.sh

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh docker_build/appimage-appsdir*.AppImage*
